title = "Example config file for this bot."

[schedule]
start_booking_time_hour = 10
start_booking_time_minute = 40
start_booking_time_second = 30

[login]
member_number = 123456
password = "password123"
url = "https://mygolfclub.com/login/"

[booking]
number_of_players = 2
time = "9:00 AM"
days_from_now = 5